module.exports = {
  rules: {
    // ----- Possible Problems -------------------------------------------------
    "array-callback-return": "error",
    "no-await-in-loop": "error",
    "no-constant-binary-expression": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": "error",
    "no-new-native-nonconstructor": "error",
    "no-promise-executor-return": "error",
    "no-self-compare": "error",
    "no-template-curly-in-string": "error",
    "no-unmodified-loop-condition": "error",
    // "no-unreachable-loop": "error",
    "no-unused-private-class-members": "error",
    "no-use-before-define": ["error", "nofunc"],
    "require-atomic-updates": "error",
    "no-unsafe-optional-chaining": [
      "error",
      { disallowArithmeticOperators: true },
    ],

    // ----- Suggestions -------------------------------------------------------
    "accessor-pairs": "error",
    "arrow-body-style": "error",
    "block-scoped-var": "error",
    camelcase: "error",
    "capitalized-comments": "error",
    "class-methods-use-this": "error",
    complexity: ["error", 8],
    // "consistent-return": "error",
    "consistent-this": ["error", "self"],
    curly: "error",
    "default-case": "error",
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-notation": "error",
    eqeqeq: "error",
    "func-name-matching": "error",
    "func-names": ["error", "as-needed"],
    "func-style": ["error", "declaration"],
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "guard-for-in": "error",
    "id-length": [
      "error",
      {
        max: 32,
        min: 1,
      },
    ],
    // "id-match": "error",
    "init-declarations": ["error", "always"],
    "logical-assignment-operators": ["error", "always"],
    "max-classes-per-file": "error",
    "max-depth": "error",
    "max-len": [
      "error",
      {
        code: 120,
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        tabWidth: 1,
      },
    ],
    "max-lines": [
      "error",
      {
        max: 1024,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
    "max-lines-per-function": [
      "error",
      {
        max: 128,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
    "max-nested-callbacks": ["error", 8],
    "max-params": ["error", { max: 8 }],
    "max-statements": ["error", 16],
    // "multiline-comment-style": "error",
    "new-cap": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-console": "error",
    // "no-continue": "error",
    "no-div-regex": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-empty-static-block": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    // "no-inline-comments": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    // "no-magic-numbers": "error",
    "no-multi-assign": "error",
    "no-multi-str": "error",
    "no-negated-condition": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-octal-escape": "error",
    // "no-param-reassign": "error",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-proto": "error",
    // "no-restricted-exports": "error",
    // "no-restricted-global": "error",
    // "no-restricted-imports": "error",
    // "no-restricted-properties": "error",
    "no-restricted-syntax": "error",
    "no-return-assign": ["error", "always"],
    "no-script-url": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-ternary": "error",
    "no-throw-literal": "error",
    "no-undef-init": "error",
    "no-undefined": "error",
    "no-underscore-dangle": "error",
    "no-unneeded-ternary": "error",
    "no-unused-expressions": [
      "error",
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
      },
    ],
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": "error",
    "no-warning-comments": "error",
    "object-shorthand": "error",
    // "one-var": "error",
    "operator-assignment": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    // "prefer-named-capture-group": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    radix: ["error", "as-needed"],
    "require-await": "error",
    "require-unicode-regexp": "error",
    "sort-imports": "error",
    // "sort-keys": "error",
    // "sort-vars": "error",
    strict: ["error", "safe"],
    "symbol-description": "error",
    "vars-on-top": "error",
    yoda: "error",

    // ----- Layout & Formatting -----------------------------------------------
    // "line-comment-position": "error",
    "unicode-bom": "error",
  },
};
