module.exports = {
  rules: {
    // "jsdoc/check-examples": "error",
    "jsdoc/check-indentation": "error",
    // "jsdoc/check-line-alignment": "error",
    "jsdoc/check-syntax": "error",
    "jsdoc/informative-docs": "error",
    // "jsdoc/match-description": "error",
    // "jsdoc/match-name": "error",
    // "jsdoc/no-bad-blocks": "error",
    // "jsdoc/no-defaults": "error",
    // "jsdoc/no-missing-syntax": "error",
    // "jsdoc/no-restricted-syntax": "error",
    // "jsdoc/no-types": "error",
    "jsdoc/require-asterisk-prefix": "error",
    // "jsdoc/require-description": "error",
    "jsdoc/require-description-complete-sentence": "error",
    // "jsdoc/require-example": "error",
    // "jsdoc/require-file-overview": "error",
    // "jsdoc/require-hyphen-before-param-description": "error",
    "jsdoc/require-returns-description": "off", // Override
    "jsdoc/require-throws": "error",
    // "jsdoc/sort-tags": "error",
    // "jsdoc/text-escaping": "error",
  },
};
