language: node_js

node_js:
  - 'node'
  - 'lts/*'

env:
  global:
    - CC_TEST_REPORTER_ID=a9a320ed0e3f0d99ae12fc25fa79ae52307ff53b85db5ceb5b3ef1e9628b9e45

matrix:
  fast_finish: true

install:
  - npm install

after_script:
  - cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
