language: node_js

node_js:
  - node
  - lts/*

env:
  global:
    - CC_TEST_REPORTER_ID=a9a320ed0e3f0d99ae12fc25fa79ae52307ff53b85db5ceb5b3ef1e9628b9e45

before_script:
  - wget -O ./cctr https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cctr
  - ./cctr before-build

after_script:
  - ./cctr after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: deploy
      script: npm pack
      deploy:
        - provider: npm
          email: me@mgsisk.com
          api_key:
            secure: nK8AV9YUOF+xBERlgOVpzvcJ9/LAoEfktdoa1IQeyxuQtvaxtsblG34/2eqsC8jeTkrqmMIswvAYrI7hEnQNFtdZKSkH0DMnB5fPFYFOA9C4OHhRxpeVlM6U7PxFNhWRDTKHjcygUs9mN1a5WRS1K/kMDF9ub/2SXM0AP7nbuOplTxIn9AmGZgfvu6tuvV8FBtXoft/imAAXOxQDx2ZsZFj7/ifaHacwdlksEMKnSKb4FMYg7PNVl/Zn4Ca2a4cxhv8qHeqcUbsjldU4x8nfS06cf+2/IO3In/wFVfiZ6zmR3rLUsTCYw7o0E91OAQG8t9I7GZTaCPB0qXFW/m/shZ+jksi2r3B1YpB/njhRPwSjJEHcWSRiUePEsJjDZ1pULoJN0EG0trYUCScYnkogcKZ+XAhJQzu2SK/Lg/GoMZoM4wijTl5oY69K1+xQDpX5oo7IyVi8YtRrQbM02WFEPUzowGAULVwydE7nYJyQHy02InFiLl/AB/dri9a9Ubjsp+UMMCO8tSQCO4aJTofxoLgiCADo0u1C6jxZXOTvxg3zz/U7qy3ENSZlNo23EJOz2SqoM3xZPs8ruyUKIPeRnCb5fHsCInCrhyhvK7aMGFWBA5kN5MYdBzdpKGxplS23TYPEKx4rTAeM4ZgDvPbBG3qzsIlesVUbMIVUNVuWYQ8=
          on:
            repo: mgsisk/eslint-config
            tags: true
        - provider: npm
          registry: https://npm.pkg.github.com
          email: me@mgsisk.com
          api_key:
            secure: TM7RYNpRrVZkLCy57WkUicVgZIndjiEyw6tN50rPZrNAmdyUF/l2KW1xaZrwlZwfL7osMciJW85KGwVCFnr5FOHJwZetVI9Y7YtEG8TTSRTG9fxr+HOE3pPlIzggplkBh6PEGz5zCGEpriagjlUc2gXmM5xO5keoQ5GfiU/2KMpTlFKqKdRlaIm0DwQYMNFyHD58QrFDkvtVzKWKY/J5lbfAJO1w6MGgd7UgGuZHw1xLB85NOI/X0+DvrXmJqbiReSAy42HEdMbGXCUdk6hJK+FXjdUgyxyONW3+2vNyCrU7SLRWayYEQfk4qLBdk5EmFlqLBBPqBJXkX8M823F1iq83JvANQ64vlWsWCxkGrSfE4S8B9bjZHUVrUgE2zw65lkG9Pc9+aIGpMd/ep7e/KE0OPVm3m1i0/pnrD5LhfBA5U1ErKAZX/88vs7mNCbqZjx0hVpMyaSSKJni9hazfHWLerc8A+omtOBIUzE0J98whsTZDRZ+mQyU6v3XG3Nnm7vBV4wCqKa06eqEVLQMC9vji14ckl3kUWij0zYAxJQyO6fZi4rmTUIIBvJ/WgBkRuopE43C1/1zDN/ag7nVEqqJn1xGPtkHUxnymGJkZvHakpXnbwd+fYofo2eYrLAkzv9jq7uCM0syJYYVz0FmJCskVOPi4EzkUSP5nQRpzGQY=
          edge:
            branch: master
          on:
            repo: mgsisk/eslint-config
            tags: true
        - provider: releases
          skip_cleanup: true
          file_glob: true
          file: mgsisk-eslint-config-*.tgz
          api_key:
            secure: TM7RYNpRrVZkLCy57WkUicVgZIndjiEyw6tN50rPZrNAmdyUF/l2KW1xaZrwlZwfL7osMciJW85KGwVCFnr5FOHJwZetVI9Y7YtEG8TTSRTG9fxr+HOE3pPlIzggplkBh6PEGz5zCGEpriagjlUc2gXmM5xO5keoQ5GfiU/2KMpTlFKqKdRlaIm0DwQYMNFyHD58QrFDkvtVzKWKY/J5lbfAJO1w6MGgd7UgGuZHw1xLB85NOI/X0+DvrXmJqbiReSAy42HEdMbGXCUdk6hJK+FXjdUgyxyONW3+2vNyCrU7SLRWayYEQfk4qLBdk5EmFlqLBBPqBJXkX8M823F1iq83JvANQ64vlWsWCxkGrSfE4S8B9bjZHUVrUgE2zw65lkG9Pc9+aIGpMd/ep7e/KE0OPVm3m1i0/pnrD5LhfBA5U1ErKAZX/88vs7mNCbqZjx0hVpMyaSSKJni9hazfHWLerc8A+omtOBIUzE0J98whsTZDRZ+mQyU6v3XG3Nnm7vBV4wCqKa06eqEVLQMC9vji14ckl3kUWij0zYAxJQyO6fZi4rmTUIIBvJ/WgBkRuopE43C1/1zDN/ag7nVEqqJn1xGPtkHUxnymGJkZvHakpXnbwd+fYofo2eYrLAkzv9jq7uCM0syJYYVz0FmJCskVOPi4EzkUSP5nQRpzGQY=
          on:
            repo: mgsisk/eslint-config
            tags: true
