name: build

on: [pull_request, push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm clean-install
      - run: npm test

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm clean-install
      - id: set_vars
        run: |
          PACK=$(npm pack | tail -n 1)
          echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
          echo "::set-output name=tag_vers::${GITHUB_REF#refs/tags/v}"
          echo "::set-output name=tar_name::$PACK"
      - id: read_changelog
        uses: mindsers/changelog-reader-action@master
        with:
          version: ${{ steps.set_vars.outputs.tag_vers }}
          path: docs/CHANGELOG.md
      - id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.read_changelog.outputs.changes }}
          tag_name: ${{ steps.set_vars.outputs.tag_name }}
          prerelease: ${{ steps.read_changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.read_changelog.outputs.status == 'unreleased' }}
      - uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/gzip
          asset_name: ${{ steps.set_vars.outputs.tar_name }}
          asset_path: ./${{ steps.set_vars.outputs.tar_name }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm clean-install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          registry-url: https://npm.pkg.github.com
      - run: npm clean-install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
